### PR TITLE
proposed changes

### PR DESCRIPTION
**Pull request by alansrobotlab**
Here's a growing list of things that I kept manually doing after every fusion2urdf generation, and thought I'd take a few hours and move them into the codebase.  

The last few are the most fun.

With this change fusion2urdf generates a fully self contained description package.  All you need to do is to copy it into your catkin_ws/src directory.

Also I'm suggesting the move from urdf to xacro.  It does make the scripts a little more complicated, but solves so many problems when using the tool for real work.

Thanks!

Alan

### CODE REVIEW

**Comment by nyxaria** [comment]
This looks really awesome, thanks for your hard work!

**Comment by nyxaria** [comment]
I will review this if I have some time later

**Comment by blubbi321** [comment]
@alansrobotlab when converting using your changes I get a working display.launch file (yay :)), however as soon as I shut that down and launch gazebo.launch and controller.launch after it seems that the tf tree is split apart at the joints. This problem is not there when running display.launch ..

Any idea what might be the cause of this?

**Comment by blubbi321** [comment]
> @alansrobotlab when converting using your changes I get a working display.launch file (yay :)), however as soon as I shut that down and launch gazebo.launch and controller.launch after it seems that the tf tree is split apart at the joints. This problem is not there when running display.launch ..
> 
> Any idea what might be the cause of this?

Apologies, it was a namespace issue on my end (the robot_state_publisher didnt get the input from /joint_states)

**Comment by syuntoku14** [comment]
I'm really sorry for the late response.
Thank you for your great work!

**Pull request merged**
